package router

import (
	"github.com/songquanpeng/one-api/controller"
	"github.com/songquanpeng/one-api/controller/auth"
	"github.com/songquanpeng/one-api/middleware"

	"github.com/gin-contrib/gzip"
	"github.com/gin-gonic/gin"
)

func SetApiRouter(router *gin.Engine) {
	apiRouter := router.Group("/api")
	apiRouter.Use(gzip.Gzip(gzip.DefaultCompression))
	apiRouter.Use(middleware.GlobalAPIRateLimit())
	{
		apiRouter.GET("/status", controller.GetStatus)
		apiRouter.GET("/ratio_config", controller.GetPublicRatioConfig)
		apiRouter.POST("/pay/wechat/notify", controller.WeChatPayNotifyHandler)
		apiRouter.GET("/models", middleware.UserAuth(), controller.DashboardListModels)
		apiRouter.GET("/notice", controller.GetNotice)
		apiRouter.GET("/about", controller.GetAbout)
		apiRouter.GET("/home_page_content", controller.GetHomePageContent)
		apiRouter.POST("/verify", middleware.UserAuth(), middleware.CriticalRateLimit(), controller.UniversalVerify)
		apiRouter.GET("/verification", middleware.CriticalRateLimit(), middleware.TurnstileCheck(), controller.SendEmailVerification)
		apiRouter.GET("/reset_password", middleware.CriticalRateLimit(), middleware.TurnstileCheck(), controller.SendPasswordResetEmail)
		apiRouter.POST("/user/reset", middleware.CriticalRateLimit(), controller.ResetPassword)
		apiRouter.GET("/oauth/github", middleware.CriticalRateLimit(), auth.GitHubOAuth)
		apiRouter.GET("/oauth/oidc", middleware.CriticalRateLimit(), auth.OidcAuth)
		apiRouter.GET("/oauth/lark", middleware.CriticalRateLimit(), auth.LarkOAuth)
		apiRouter.GET("/oauth/state", middleware.CriticalRateLimit(), auth.GenerateOAuthCode)
		apiRouter.GET("/oauth/wechat", middleware.CriticalRateLimit(), auth.WeChatAuth)
		apiRouter.GET("/oauth/wechat/bind", middleware.CriticalRateLimit(), middleware.UserAuth(), auth.WeChatBind)
		apiRouter.GET("/oauth/email/bind", middleware.CriticalRateLimit(), middleware.UserAuth(), controller.EmailBind)
		apiRouter.POST("/topup", middleware.AdminAuth(), middleware.PlatformConsoleOnly(), controller.AdminTopUp)

		userRoute := apiRouter.Group("/user")
		{
			userRoute.POST("/register", middleware.CriticalRateLimit(), middleware.TurnstileCheck(), controller.Register)
			userRoute.GET("/login/request-proof", middleware.CriticalRateLimit(), controller.LoginRequestProofIssue)
			userRoute.GET("/login/captcha", middleware.CriticalRateLimit(), controller.LoginCaptchaChallenge)
			userRoute.POST("/login", middleware.CriticalRateLimit(), middleware.TurnstileCheck(), controller.Login)
			userRoute.POST("/login/2fa", middleware.CriticalRateLimit(), controller.Verify2FALogin)
			userRoute.GET("/logout", controller.Logout)

			selfRoute := userRoute.Group("/")
			selfRoute.Use(middleware.UserAuth())
			{
				selfRoute.GET("/dashboard", controller.GetUserDashboard)
				selfRoute.GET("/self", controller.GetSelf)
				selfRoute.GET("/nacos-console-token", controller.GetNacosConsoleEmbedToken)
				selfRoute.PUT("/self", controller.UpdateSelf)
				selfRoute.DELETE("/self", controller.DeleteSelf)
				selfRoute.GET("/token", controller.GenerateAccessToken)
				selfRoute.GET("/aff", controller.GetAffCode)
				selfRoute.POST("/tenant_upgrade", controller.ApplyTenantUpgrade)
				selfRoute.POST("/topup", controller.TopUp)
				selfRoute.GET("/available_models", controller.GetUserAvailableModels)
				selfRoute.GET("/available_models_detail", controller.GetUserAvailableModelsDetail)
				selfRoute.GET("/model_square", controller.GetUserModelSquare)
				selfRoute.GET("/pay/channels", controller.GetUserPaymentChannels)
				selfRoute.POST("/pay/wechat/native", controller.CreateWeChatNativeOrder)
				selfRoute.GET("/pay/order/:order_no", controller.GetPaymentOrderStatus)
				selfRoute.GET("/2fa/status", controller.Get2FAStatus)
				selfRoute.POST("/2fa/setup", controller.Setup2FA)
				selfRoute.POST("/2fa/enable", controller.Enable2FA)
				selfRoute.POST("/2fa/disable", controller.Disable2FA)
				selfRoute.POST("/2fa/backup_codes", controller.RegenerateBackupCodes)
				selfRoute.POST("/s3/enable", controller.UserS3Enable)
				selfRoute.POST("/s3/disable", controller.UserS3Disable)
				selfRoute.POST("/s3/regenerate_secret", controller.UserS3RegenerateSecret)
				selfRoute.POST("/s3/rotate_keys", controller.UserS3RotateKeys)
			}

			adminRoute := userRoute.Group("/")
			adminRoute.Use(middleware.AdminAuth(), middleware.PlatformConsoleOnly())
			{
				adminRoute.GET("/paged", controller.GetUsersPaged)
				adminRoute.POST("/:id/promote_super_admin", middleware.RootAuth(), controller.PromoteUserToSuperAdmin)
				adminRoute.POST("/:id/demote_super_admin", middleware.RootAuth(), controller.DemoteSuperAdmin)
				adminRoute.GET("/2fa/stats", controller.Admin2FAStats)
				adminRoute.GET("/", controller.GetAllUsers)
				adminRoute.GET("/search", controller.SearchUsers)
				adminRoute.GET("/:id", controller.GetUser)
				adminRoute.POST("/", controller.CreateUser)
				adminRoute.POST("/manage", controller.ManageUser)
				adminRoute.PUT("/", controller.UpdateUser)
				adminRoute.DELETE("/:id/2fa", controller.AdminDisable2FA)
				adminRoute.DELETE("/:id", controller.DeleteUser)
			}
		}
		optionRoute := apiRouter.Group("/option")
		optionRoute.Use(middleware.SuperAdminAuth())
		{
			optionRoute.GET("/", controller.GetOptions)
			optionRoute.PUT("/", controller.UpdateOption)
		}
		paymentAccessRoute := apiRouter.Group("/payment/access")
		paymentAccessRoute.Use(middleware.SuperAdminAuth())
		{
			paymentAccessRoute.GET("", controller.ListPaymentAccess)
			paymentAccessRoute.PUT("", controller.SetPaymentAccess)
			paymentAccessRoute.DELETE("", controller.DeletePaymentAccess)
		}
		ratioSyncRoute := apiRouter.Group("/ratio_sync")
		ratioSyncRoute.Use(middleware.RootAuth())
		{
			ratioSyncRoute.GET("/channels", controller.GetSyncableChannels)
			ratioSyncRoute.POST("/fetch", controller.FetchUpstreamRatios)
			ratioSyncRoute.GET("/batches", controller.ListUpstreamSyncBatches)
			ratioSyncRoute.GET("/batches/latest", controller.GetLatestUpstreamSyncBatch)
			ratioSyncRoute.GET("/batches/:id", controller.GetUpstreamSyncBatch)
			ratioSyncRoute.GET("/batches/:id/diffs", controller.ListUpstreamSyncBatchDiffs)
			ratioSyncRoute.PUT("/batches/:id/selections", controller.SaveUpstreamSyncBatchSelections)
			ratioSyncRoute.POST("/batches/:id/selections/select_all", controller.SelectAllUpstreamSyncBatch)
			ratioSyncRoute.POST("/batches/:id/apply", controller.ApplyUpstreamSyncBatch)
			ratioSyncRoute.GET("/compare/diffs", controller.CompareUpstreamSync)
			ratioSyncRoute.GET("/versions", controller.ListPricingVersionBlocks)
			ratioSyncRoute.GET("/versions/:block_id", controller.ListPricingBlockVersions)
			ratioSyncRoute.POST("/versions/activate", controller.ActivatePricingVersion)
			ratioSyncRoute.POST("/apply", controller.ApplyPricingSync)
		}
		pricingEntryRoute := apiRouter.Group("/pricing_entries")
		pricingEntryRoute.Use(middleware.RootAuth())
		{
			pricingEntryRoute.GET("/blocks", controller.ListPricingEntryBlocks)
			pricingEntryRoute.GET("/", controller.ListPricingEntries)
			pricingEntryRoute.POST("/", controller.CreatePricingEntry)
			pricingEntryRoute.PUT("/:id", controller.UpdatePricingEntry)
			pricingEntryRoute.DELETE("/:id", controller.DeletePricingEntry)
		}
		platformTenantRead := apiRouter.Group("/platform/tenants")
		platformTenantRead.Use(middleware.AdminAuth(), middleware.PlatformConsoleOnly())
		{
			platformTenantRead.GET("/", controller.PlatformListTenants)
			platformTenantRead.GET("/options", controller.PlatformListTenantOptions)
			platformTenantRead.GET("/upgrades", controller.PlatformListTenantUpgrades)
		}
		platformTenantWrite := apiRouter.Group("/platform/tenants")
		platformTenantWrite.Use(middleware.SuperAdminAuth(), middleware.PlatformConsoleOnly())
		{
			platformTenantWrite.POST("/", controller.PlatformCreateTenant)
			platformTenantWrite.POST("/upgrades/:id/approve", controller.PlatformApproveTenantUpgrade)
			platformTenantWrite.POST("/upgrades/:id/reject", controller.PlatformRejectTenantUpgrade)
			platformTenantWrite.PUT("/:id/billing", controller.PlatformUpdateTenantBilling)
			platformTenantWrite.GET("/:id/billing_rules", controller.PlatformGetTenantBillingRules)
			platformTenantWrite.POST("/:id/billing_rules", controller.PlatformCreateTenantBillingRule)
			platformTenantWrite.PUT("/:id/billing_rules/:rule_id", controller.PlatformUpdateTenantBillingRule)
			platformTenantWrite.DELETE("/:id/billing_rules/:rule_id", controller.PlatformDeleteTenantBillingRule)
		}
		platformReports := apiRouter.Group("/platform/reports")
		platformReports.Use(middleware.AdminAuth(), middleware.PlatformConsoleOnly())
		{
			platformReports.GET("/billing", controller.PlatformGetBillingReport)
			platformReports.GET("/billing/export", controller.PlatformExportBillingReport)
		}
		modelCatalogRoute := apiRouter.Group("/model_catalog")
		modelCatalogRoute.Use(middleware.AdminAuth(), middleware.PlatformConsoleOnly())
		{
			modelCatalogRoute.GET("/", controller.GetModelCatalogAdmin)
			modelCatalogRoute.GET("/providers", controller.GetModelCatalogProviders)
			modelCatalogRoute.GET("/model_ids", controller.GetModelCatalogModelIDs)
			modelCatalogRoute.GET("/editor_options", controller.GetModelCatalogEditorOptions)
			modelCatalogRoute.POST("/", controller.PostModelCatalogAdmin)
			modelCatalogRoute.PUT("/", controller.PutModelCatalogAdmin)
			modelCatalogRoute.POST("/sync", controller.PostModelCatalogSync)
			modelCatalogRoute.DELETE("/:id", controller.DeleteModelCatalogAdmin)
		}
		channelRoute := apiRouter.Group("/channel")
		channelRoute.Use(middleware.AdminAuth(), middleware.PlatformConsoleOnly())
		{
			channelRoute.GET("/", controller.GetAllChannels)
			channelRoute.GET("/search", controller.SearchChannels)
			channelRoute.GET("/models", controller.ListAllModels)
			channelRoute.GET("/models_enabled", controller.ListEnabledChannelModels)
			channelRoute.GET("/fetch_models/:id", controller.FetchUpstreamChannelModels)
			channelRoute.POST("/fetch_upstream_models_preview", controller.PreviewFetchUpstreamChannelModels)
			channelRoute.POST("/test_models_preview", controller.PreviewTestChannelModels)
			channelRoute.POST("/test_models/jobs", controller.StartChannelModelTestJob)
			channelRoute.GET("/test_models/jobs/status", controller.GetChannelModelTestJobStatus)
			channelRoute.POST("/test_models/jobs/control", controller.ControlChannelModelTestJob)
			channelRoute.GET("/:id/model_test_results", controller.GetChannelModelTestResults)
			channelRoute.POST("/fix", controller.FixChannelsAbilities)
			channelRoute.POST("/batch", controller.DeleteChannelBatch)
			channelRoute.POST("/copy/:id", controller.CopyChannel)
			channelRoute.GET("/:id", controller.GetChannel)
			channelRoute.POST("/:id/key", middleware.CriticalRateLimit(), middleware.SecureVerificationRequired(), controller.GetChannelKey)
			channelRoute.GET("/test", controller.TestChannels)
			channelRoute.GET("/test/:id", controller.TestChannel)
			channelRoute.GET("/update_balance", controller.UpdateAllChannelsBalance)
			channelRoute.GET("/update_balance/:id", controller.UpdateChannelBalance)
			channelRoute.POST("/", controller.AddChannel)
			channelRoute.PUT("/", controller.UpdateChannel)
			channelRoute.DELETE("/disabled", controller.DeleteDisabledChannel)
			channelRoute.DELETE("/:id", controller.DeleteChannel)
		}

		routingRoute := apiRouter.Group("/routing")
		routingRoute.Use(middleware.AdminAuth(), middleware.PlatformConsoleOnly())
		{
			routingRoute.GET("/metrics-day", controller.GetRoutingMetricsDay)
			routingRoute.GET("/channel-preview", controller.GetRoutingChannelPreview)
			routingRoute.GET("/circuit-states", controller.GetRoutingCircuitStates)
			routingRoute.POST("/manual-weight", controller.PostRoutingManualWeight)
			routingRoute.GET("/policy-bundle", controller.GetRoutingPolicyBundle)
			routingRoute.POST("/validate-alias-policy", controller.PostRoutingValidateAliasPolicy)
			routingRoute.GET("/fuse-events", controller.GetRoutingFuseEvents)
			routingRoute.GET("/timeseries", controller.GetRoutingTimeseries)
			routingRoute.GET("/model-catalog", controller.GetRoutingModelCatalog)
			routingRoute.POST("/reset-auto-weight", controller.PostRoutingResetAutoWeight)
		}

		tokenRoute := apiRouter.Group("/token")
		tokenRoute.Use(middleware.UserAuth())
		{
			tokenRoute.GET("/", controller.GetAllTokens)
			tokenRoute.GET("/search", controller.SearchTokens)
			tokenRoute.GET("/:id", controller.GetToken)
			tokenRoute.POST("/", controller.AddToken)
			tokenRoute.PUT("/", controller.UpdateToken)
			tokenRoute.DELETE("/:id", controller.DeleteToken)
		}
		redemptionRoute := apiRouter.Group("/redemption")
		redemptionRoute.Use(middleware.AdminAuth(), middleware.PlatformConsoleOnly())
		{
			redemptionRoute.GET("/", controller.GetAllRedemptions)
			redemptionRoute.GET("/search", controller.SearchRedemptions)
			redemptionRoute.GET("/:id", controller.GetRedemption)
			redemptionRoute.POST("/", controller.AddRedemption)
			redemptionRoute.PUT("/", controller.UpdateRedemption)
			redemptionRoute.DELETE("/:id", controller.DeleteRedemption)
		}
		logAdmin := apiRouter.Group("/log")
		logAdmin.Use(middleware.AdminAuth(), middleware.PlatformConsoleOnly())
		logAdmin.GET("/", controller.GetAllLogs)
		logAdmin.DELETE("/", controller.DeleteHistoryLogs)
		logAdmin.GET("/stat", controller.GetLogsStat)
		logAdmin.GET("/search", controller.SearchAllLogs)
		logAdmin.GET("/billing", controller.GetBillingSummary)
		logAdmin.GET("/export", controller.ExportLogs)
		apiRouter.GET("/log/token", middleware.TokenAuth(), controller.GetLogByKey)
		apiRouter.GET("/log/self/stat", middleware.UserAuth(), controller.GetLogsSelfStat)
		apiRouter.GET("/log/self", middleware.UserAuth(), controller.GetUserLogs)
		apiRouter.GET("/log/self/search", middleware.UserAuth(), controller.SearchUserLogs)
		groupRoute := apiRouter.Group("/group")
		groupRoute.Use(middleware.AdminAuth(), middleware.PlatformConsoleOnly())
		{
			groupRoute.GET("/", controller.GetGroups)
		}
		globalAccessRoute := apiRouter.Group("/global_access")
		globalAccessRoute.Use(middleware.AdminAuth(), middleware.PlatformConsoleOnly())
		{
			globalAccessRoute.GET("/mode", controller.GetGlobalAccessMode)
			globalAccessRoute.PUT("/mode", controller.UpdateGlobalAccessMode)
			globalAccessRoute.GET("/whitelist", controller.GetGlobalWhitelist)
			globalAccessRoute.POST("/whitelist", controller.CreateGlobalWhitelist)
			globalAccessRoute.DELETE("/whitelist/:id", controller.DeleteGlobalWhitelist)
			globalAccessRoute.GET("/blacklist", controller.GetGlobalBlacklist)
			globalAccessRoute.POST("/blacklist", controller.CreateGlobalBlacklist)
			globalAccessRoute.DELETE("/blacklist/:id", controller.DeleteGlobalBlacklist)
		}
		nacosAdmin := apiRouter.Group("/nacos")
		nacosAdmin.Use(middleware.UserAuth(), middleware.NacosTenantDelegatedGate())
		{
			nacosAdmin.GET("/registry/info", controller.GetNacosRegistryInfo)
			nacosAdmin.GET("/namespaces/options", controller.ListNacosNamespaceOptions)
			nacosAdmin.GET("/namespaces/detail", controller.GetNacosNamespaceDetailAdmin)
			nacosAdmin.GET("/namespaces", controller.ListNacosRegistryNamespaces)
			nacosAdmin.POST("/namespaces", controller.CreateNacosRegistryNamespace)
			nacosAdmin.PUT("/namespaces", controller.UpdateNacosRegistryNamespace)
			nacosAdmin.DELETE("/namespaces/:namespaceId", controller.DeleteNacosRegistryNamespace)
			nacosAdmin.GET("/cs/configs", controller.ListNacosCsConfigsAdmin)
			nacosAdmin.GET("/cs/configs/detail", controller.GetNacosCsConfigDetailAdmin)
			nacosAdmin.POST("/cs/configs/publish", controller.PublishNacosCsConfigAdmin)
			nacosAdmin.GET("/cs/configs/history", controller.ListNacosCsConfigHistoryAdmin)
			nacosAdmin.POST("/cs/configs/rollback", controller.RollbackNacosCsConfigAdmin)
			nacosAdmin.DELETE("/cs/configs/item", controller.DeleteNacosCsConfigAdmin)
			nacosAdmin.GET("/skills/detail", controller.GetNacosSkillDetailAdmin)
			nacosAdmin.GET("/skills", controller.ListNacosSkillsAdmin)
			nacosAdmin.POST("/skills/upload", controller.UploadNacosSkillAdmin)
			nacosAdmin.PUT("/skills/metadata", controller.UpdateNacosSkillMetadataAdmin)
			nacosAdmin.DELETE("/skills/item", controller.DeleteNacosSkillAdmin)
			nacosAdmin.POST("/skills/submit", controller.SubmitNacosSkillAdmin)
			nacosAdmin.POST("/skills/publish", controller.PublishNacosSkillAdmin)
			nacosAdmin.POST("/skills/version/online", controller.NacosSkillVersionOnlineAdmin)
			nacosAdmin.POST("/skills/version/offline", controller.NacosSkillVersionOfflineAdmin)
			nacosAdmin.GET("/skills/download", controller.DownloadNacosSkillZipAdmin)
			nacosAdmin.POST("/skills/labels", controller.UpdateNacosSkillLabelsAdmin)
			nacosAdmin.GET("/agentspecs/detail", controller.GetNacosAgentSpecDetailAdmin)
			nacosAdmin.PUT("/agentspecs/metadata", controller.UpdateNacosAgentSpecMetadataAdmin)
			nacosAdmin.DELETE("/agentspecs/item", controller.DeleteNacosAgentSpecAdmin)
			nacosAdmin.POST("/agentspecs/upload", controller.UploadNacosAgentSpecAdmin)
			nacosAdmin.POST("/agentspecs/submit", controller.SubmitNacosAgentSpecAdmin)
			nacosAdmin.POST("/agentspecs/publish", controller.PublishNacosAgentSpecAdmin)
			nacosAdmin.POST("/agentspecs/labels", controller.UpdateNacosAgentSpecLabelsAdmin)
			nacosAdmin.GET("/agentspecs/download", controller.DownloadNacosAgentSpecZipAdmin)
			nacosAdmin.GET("/mcp", controller.ListNacosMcpAdmin)
			nacosAdmin.GET("/mcp/detail", controller.GetNacosMcpDetailAdmin)
			nacosAdmin.POST("/mcp", controller.UpsertNacosMcpAdmin)
			nacosAdmin.DELETE("/mcp", controller.DeleteNacosMcpAdmin)
			nacosAdmin.GET("/a2a", controller.ListNacosA2AAdmin)
			nacosAdmin.GET("/a2a/detail", controller.GetNacosA2ADetailAdmin)
			nacosAdmin.POST("/a2a", controller.UpsertNacosA2AAdmin)
			nacosAdmin.DELETE("/a2a", controller.DeleteNacosA2AAdmin)
			nacosAdmin.GET("/prompts", controller.ListNacosPromptsAdmin)
			nacosAdmin.GET("/prompts/detail", controller.GetNacosPromptDetailAdmin)
			nacosAdmin.POST("/prompts/header", controller.UpsertNacosPromptHeaderAdmin)
			nacosAdmin.POST("/prompts/version", controller.AddNacosPromptVersionAdmin)
			nacosAdmin.POST("/prompts/submit", controller.SubmitNacosPromptAdmin)
			nacosAdmin.POST("/prompts/publish", controller.PublishNacosPromptAdmin)
			nacosAdmin.POST("/prompts/labels", controller.UpdateNacosPromptLabelsAdmin)
			nacosAdmin.DELETE("/prompts/item", controller.DeleteNacosPromptAdmin)
			nacosAdmin.GET("/pipelines", controller.ListNacosPipelinesAdmin)
			nacosAdmin.GET("/pipelines/detail", controller.GetNacosPipelineDetailAdmin)
			nacosAdmin.POST("/pipelines/run-scan", controller.RunNacosPipelineScanAdmin)
			nacosAdmin.GET("/agentspecs", controller.ListNacosAgentSpecsAdmin)
			nacosAdmin.GET("/users/search", controller.NacosSearchUsersForACL)
			nacosAdmin.GET("/users/:id/acl", controller.GetNacosUserACL)
			nacosAdmin.PUT("/users/:id/acl", controller.PutNacosUserACL)
		}

		tenantConsole := apiRouter.Group("/tenant_console")
		tenantConsole.Use(middleware.UserAuth(), middleware.TenantConsoleMemberGate(), middleware.TenantAdminConsoleOnly())
		{
			tenantConsole.GET("/meta/editor_options", controller.GetModelCatalogEditorOptions)
			tenantConsole.GET("/meta/model_catalog/providers", controller.GetModelCatalogProviders)
			tenantConsole.GET("/meta/model_catalog/model_ids", controller.GetModelCatalogModelIDs)
			tenantConsole.POST("/meta/channel/test_models_preview", controller.PreviewTestChannelModels)
			tenantConsole.POST("/meta/channel/test_models/jobs", controller.TenantStartChannelModelTestJob)
			tenantConsole.GET("/meta/channel/test_models/jobs/status", controller.TenantGetChannelModelTestJobStatus)
			tenantConsole.POST("/meta/channel/test_models/jobs/control", controller.TenantControlChannelModelTestJob)
			tenantConsole.GET("/meta/channel/:id/model_test_results", controller.TenantGetChannelModelTestResults)
			tenantConsole.GET("/meta/groups", controller.GetGroups)
			tenantConsole.GET("/meta/all_models", controller.ListAllModels)
			tenantConsole.GET("/meta/channels_for_acl", controller.TenantConsoleChannelsForACL)
			tenantConsole.GET("/meta/tenant", controller.TenantConsoleMetaTenant)
			tenantConsole.GET("/reports/billing", controller.TenantGetBillingReport)
			tenantConsole.GET("/reports/billing/export", controller.TenantExportBillingReport)
			tenantConsole.GET("/users", controller.TenantConsoleListUsers)
			tenantConsole.GET("/users/search", controller.TenantConsoleSearchUsers)
			tenantConsole.GET("/users/:id/profile", controller.TenantConsoleGetUserProfile)
			tenantConsole.GET("/users/:id/available_models", controller.TenantConsoleUserAvailableModels)
			tenantConsole.GET("/users/:id/available_models_detail", controller.TenantConsoleUserAvailableModelsDetail)
			tenantConsole.GET("/users/:id/tokens/search", controller.TenantConsoleSearchTokens)
			tenantConsole.GET("/users/:id/tokens/:tid", controller.TenantConsoleGetToken)
			tenantConsole.GET("/users/:id/tokens", controller.TenantConsoleListTokens)
			tenantConsole.POST("/users/:id/tokens", controller.TenantConsoleAddToken)
			tenantConsole.PUT("/users/:id/tokens", controller.TenantConsoleUpdateToken)
			tenantConsole.DELETE("/users/:id/tokens/:tid", controller.TenantConsoleDeleteToken)
			tenantConsole.POST("/users", controller.TenantConsoleCreateUser)
			tenantConsole.PUT("/users", controller.TenantConsoleUpdateUser)
			tenantConsole.DELETE("/users/:id", controller.TenantConsoleDeleteUser)
			tenantConsole.GET("/channels", controller.TenantConsoleListChannels)
			tenantConsole.GET("/channels/search", controller.TenantConsoleSearchChannels)
			tenantConsole.POST("/channels", controller.TenantConsoleAddChannel)
			tenantConsole.PUT("/channels", controller.TenantConsoleUpdateChannel)
			tenantConsole.DELETE("/channels/:id", controller.TenantConsoleDeleteChannel)
		}
	}
}
