package router

import (
	"github.com/songquanpeng/one-api/controller"
	"github.com/songquanpeng/one-api/controller/auth"
	"github.com/songquanpeng/one-api/middleware"

	"github.com/gin-contrib/gzip"
	"github.com/gin-gonic/gin"
)

func SetApiRouter(router *gin.Engine) {
	apiRouter := router.Group("/api")
	apiRouter.Use(gzip.Gzip(gzip.DefaultCompression))
	apiRouter.Use(middleware.GlobalAPIRateLimit())
	{
		apiRouter.GET("/status", controller.GetStatus)
		apiRouter.GET("/models", middleware.UserAuth(), controller.DashboardListModels)
		apiRouter.GET("/notice", controller.GetNotice)
		apiRouter.GET("/about", controller.GetAbout)
		apiRouter.GET("/home_page_content", controller.GetHomePageContent)
		apiRouter.POST("/verify", middleware.UserAuth(), middleware.CriticalRateLimit(), controller.UniversalVerify)
		apiRouter.GET("/verification", middleware.CriticalRateLimit(), middleware.TurnstileCheck(), controller.SendEmailVerification)
		apiRouter.GET("/reset_password", middleware.CriticalRateLimit(), middleware.TurnstileCheck(), controller.SendPasswordResetEmail)
		apiRouter.POST("/user/reset", middleware.CriticalRateLimit(), controller.ResetPassword)
		apiRouter.GET("/oauth/github", middleware.CriticalRateLimit(), auth.GitHubOAuth)
		apiRouter.GET("/oauth/oidc", middleware.CriticalRateLimit(), auth.OidcAuth)
		apiRouter.GET("/oauth/lark", middleware.CriticalRateLimit(), auth.LarkOAuth)
		apiRouter.GET("/oauth/state", middleware.CriticalRateLimit(), auth.GenerateOAuthCode)
		apiRouter.GET("/oauth/wechat", middleware.CriticalRateLimit(), auth.WeChatAuth)
		apiRouter.GET("/oauth/wechat/bind", middleware.CriticalRateLimit(), middleware.UserAuth(), auth.WeChatBind)
		apiRouter.GET("/oauth/email/bind", middleware.CriticalRateLimit(), middleware.UserAuth(), controller.EmailBind)
		apiRouter.POST("/topup", middleware.AdminAuth(), controller.AdminTopUp)

		userRoute := apiRouter.Group("/user")
		{
			userRoute.POST("/register", middleware.CriticalRateLimit(), middleware.TurnstileCheck(), controller.Register)
			userRoute.GET("/login/request-proof", middleware.CriticalRateLimit(), controller.LoginRequestProofIssue)
			userRoute.GET("/login/captcha", middleware.CriticalRateLimit(), controller.LoginCaptchaChallenge)
			userRoute.POST("/login", middleware.CriticalRateLimit(), middleware.TurnstileCheck(), controller.Login)
			userRoute.POST("/login/2fa", middleware.CriticalRateLimit(), controller.Verify2FALogin)
			userRoute.GET("/logout", controller.Logout)

			selfRoute := userRoute.Group("/")
			selfRoute.Use(middleware.UserAuth())
			{
				selfRoute.GET("/dashboard", controller.GetUserDashboard)
				selfRoute.GET("/self", controller.GetSelf)
				selfRoute.GET("/nacos-console-token", controller.GetNacosConsoleEmbedToken)
				selfRoute.PUT("/self", controller.UpdateSelf)
				selfRoute.DELETE("/self", controller.DeleteSelf)
				selfRoute.GET("/token", controller.GenerateAccessToken)
				selfRoute.GET("/aff", controller.GetAffCode)
				selfRoute.POST("/topup", controller.TopUp)
				selfRoute.GET("/available_models", controller.GetUserAvailableModels)
				selfRoute.GET("/2fa/status", controller.Get2FAStatus)
				selfRoute.POST("/2fa/setup", controller.Setup2FA)
				selfRoute.POST("/2fa/enable", controller.Enable2FA)
				selfRoute.POST("/2fa/disable", controller.Disable2FA)
				selfRoute.POST("/2fa/backup_codes", controller.RegenerateBackupCodes)
				selfRoute.POST("/s3/enable", controller.UserS3Enable)
				selfRoute.POST("/s3/disable", controller.UserS3Disable)
				selfRoute.POST("/s3/regenerate_secret", controller.UserS3RegenerateSecret)
				selfRoute.POST("/s3/rotate_keys", controller.UserS3RotateKeys)
			}

			adminRoute := userRoute.Group("/")
			adminRoute.Use(middleware.AdminAuth())
			{
				adminRoute.GET("/2fa/stats", controller.Admin2FAStats)
				adminRoute.GET("/", controller.GetAllUsers)
				adminRoute.GET("/search", controller.SearchUsers)
				adminRoute.GET("/:id", controller.GetUser)
				adminRoute.POST("/", controller.CreateUser)
				adminRoute.POST("/manage", controller.ManageUser)
				adminRoute.PUT("/", controller.UpdateUser)
				adminRoute.DELETE("/:id/2fa", controller.AdminDisable2FA)
				adminRoute.DELETE("/:id", controller.DeleteUser)
			}
		}
		optionRoute := apiRouter.Group("/option")
		optionRoute.Use(middleware.RootAuth())
		{
			optionRoute.GET("/", controller.GetOptions)
			optionRoute.PUT("/", controller.UpdateOption)
		}
		channelRoute := apiRouter.Group("/channel")
		channelRoute.Use(middleware.AdminAuth())
		{
			channelRoute.GET("/", controller.GetAllChannels)
			channelRoute.GET("/search", controller.SearchChannels)
			channelRoute.GET("/models", controller.ListAllModels)
			channelRoute.GET("/:id", controller.GetChannel)
			channelRoute.POST("/:id/key", middleware.CriticalRateLimit(), middleware.SecureVerificationRequired(), controller.GetChannelKey)
			channelRoute.GET("/test", controller.TestChannels)
			channelRoute.GET("/test/:id", controller.TestChannel)
			channelRoute.GET("/update_balance", controller.UpdateAllChannelsBalance)
			channelRoute.GET("/update_balance/:id", controller.UpdateChannelBalance)
			channelRoute.POST("/", controller.AddChannel)
			channelRoute.PUT("/", controller.UpdateChannel)
			channelRoute.DELETE("/disabled", controller.DeleteDisabledChannel)
			channelRoute.DELETE("/:id", controller.DeleteChannel)
		}
		tokenRoute := apiRouter.Group("/token")
		tokenRoute.Use(middleware.UserAuth())
		{
			tokenRoute.GET("/", controller.GetAllTokens)
			tokenRoute.GET("/search", controller.SearchTokens)
			tokenRoute.GET("/:id", controller.GetToken)
			tokenRoute.POST("/", controller.AddToken)
			tokenRoute.PUT("/", controller.UpdateToken)
			tokenRoute.DELETE("/:id", controller.DeleteToken)
		}
		redemptionRoute := apiRouter.Group("/redemption")
		redemptionRoute.Use(middleware.AdminAuth())
		{
			redemptionRoute.GET("/", controller.GetAllRedemptions)
			redemptionRoute.GET("/search", controller.SearchRedemptions)
			redemptionRoute.GET("/:id", controller.GetRedemption)
			redemptionRoute.POST("/", controller.AddRedemption)
			redemptionRoute.PUT("/", controller.UpdateRedemption)
			redemptionRoute.DELETE("/:id", controller.DeleteRedemption)
		}
		logRoute := apiRouter.Group("/log")
		logRoute.GET("/", middleware.AdminAuth(), controller.GetAllLogs)
		logRoute.DELETE("/", middleware.AdminAuth(), controller.DeleteHistoryLogs)
		logRoute.GET("/stat", middleware.AdminAuth(), controller.GetLogsStat)
		logRoute.GET("/self/stat", middleware.UserAuth(), controller.GetLogsSelfStat)
		logRoute.GET("/search", middleware.AdminAuth(), controller.SearchAllLogs)
		logRoute.GET("/self", middleware.UserAuth(), controller.GetUserLogs)
		logRoute.GET("/self/search", middleware.UserAuth(), controller.SearchUserLogs)
		groupRoute := apiRouter.Group("/group")
		groupRoute.Use(middleware.AdminAuth())
		{
			groupRoute.GET("/", controller.GetGroups)
		}
		globalAccessRoute := apiRouter.Group("/global_access")
		globalAccessRoute.Use(middleware.AdminAuth())
		{
			globalAccessRoute.GET("/mode", controller.GetGlobalAccessMode)
			globalAccessRoute.PUT("/mode", controller.UpdateGlobalAccessMode)
			globalAccessRoute.GET("/whitelist", controller.GetGlobalWhitelist)
			globalAccessRoute.POST("/whitelist", controller.CreateGlobalWhitelist)
			globalAccessRoute.DELETE("/whitelist/:id", controller.DeleteGlobalWhitelist)
			globalAccessRoute.GET("/blacklist", controller.GetGlobalBlacklist)
			globalAccessRoute.POST("/blacklist", controller.CreateGlobalBlacklist)
			globalAccessRoute.DELETE("/blacklist/:id", controller.DeleteGlobalBlacklist)
		}
		nacosAdmin := apiRouter.Group("/nacos")
		nacosAdmin.Use(middleware.AdminAuth())
		{
			nacosAdmin.GET("/registry/info", controller.GetNacosRegistryInfo)
			nacosAdmin.GET("/namespaces/options", controller.ListNacosNamespaceOptions)
			nacosAdmin.GET("/namespaces/detail", controller.GetNacosNamespaceDetailAdmin)
			nacosAdmin.GET("/namespaces", controller.ListNacosRegistryNamespaces)
			nacosAdmin.POST("/namespaces", controller.CreateNacosRegistryNamespace)
			nacosAdmin.PUT("/namespaces", controller.UpdateNacosRegistryNamespace)
			nacosAdmin.DELETE("/namespaces/:namespaceId", controller.DeleteNacosRegistryNamespace)
			nacosAdmin.GET("/cs/configs", controller.ListNacosCsConfigsAdmin)
			nacosAdmin.GET("/cs/configs/detail", controller.GetNacosCsConfigDetailAdmin)
			nacosAdmin.POST("/cs/configs/publish", controller.PublishNacosCsConfigAdmin)
			nacosAdmin.GET("/cs/configs/history", controller.ListNacosCsConfigHistoryAdmin)
			nacosAdmin.POST("/cs/configs/rollback", controller.RollbackNacosCsConfigAdmin)
			nacosAdmin.DELETE("/cs/configs/item", controller.DeleteNacosCsConfigAdmin)
			nacosAdmin.GET("/skills/detail", controller.GetNacosSkillDetailAdmin)
			nacosAdmin.GET("/skills", controller.ListNacosSkillsAdmin)
			nacosAdmin.POST("/skills/upload", controller.UploadNacosSkillAdmin)
			nacosAdmin.PUT("/skills/metadata", controller.UpdateNacosSkillMetadataAdmin)
			nacosAdmin.DELETE("/skills/item", controller.DeleteNacosSkillAdmin)
			nacosAdmin.POST("/skills/submit", controller.SubmitNacosSkillAdmin)
			nacosAdmin.POST("/skills/publish", controller.PublishNacosSkillAdmin)
			nacosAdmin.GET("/skills/download", controller.DownloadNacosSkillZipAdmin)
			nacosAdmin.POST("/skills/labels", controller.UpdateNacosSkillLabelsAdmin)
			nacosAdmin.GET("/agentspecs/detail", controller.GetNacosAgentSpecDetailAdmin)
			nacosAdmin.PUT("/agentspecs/metadata", controller.UpdateNacosAgentSpecMetadataAdmin)
			nacosAdmin.DELETE("/agentspecs/item", controller.DeleteNacosAgentSpecAdmin)
			nacosAdmin.POST("/agentspecs/upload", controller.UploadNacosAgentSpecAdmin)
			nacosAdmin.POST("/agentspecs/submit", controller.SubmitNacosAgentSpecAdmin)
			nacosAdmin.POST("/agentspecs/publish", controller.PublishNacosAgentSpecAdmin)
			nacosAdmin.POST("/agentspecs/labels", controller.UpdateNacosAgentSpecLabelsAdmin)
			nacosAdmin.GET("/agentspecs/download", controller.DownloadNacosAgentSpecZipAdmin)
			nacosAdmin.GET("/mcp", controller.ListNacosMcpAdmin)
			nacosAdmin.GET("/mcp/detail", controller.GetNacosMcpDetailAdmin)
			nacosAdmin.POST("/mcp", controller.UpsertNacosMcpAdmin)
			nacosAdmin.DELETE("/mcp", controller.DeleteNacosMcpAdmin)
			nacosAdmin.GET("/a2a", controller.ListNacosA2AAdmin)
			nacosAdmin.GET("/a2a/detail", controller.GetNacosA2ADetailAdmin)
			nacosAdmin.POST("/a2a", controller.UpsertNacosA2AAdmin)
			nacosAdmin.DELETE("/a2a", controller.DeleteNacosA2AAdmin)
			nacosAdmin.GET("/prompts", controller.ListNacosPromptsAdmin)
			nacosAdmin.GET("/prompts/detail", controller.GetNacosPromptDetailAdmin)
			nacosAdmin.POST("/prompts/header", controller.UpsertNacosPromptHeaderAdmin)
			nacosAdmin.POST("/prompts/version", controller.AddNacosPromptVersionAdmin)
			nacosAdmin.POST("/prompts/submit", controller.SubmitNacosPromptAdmin)
			nacosAdmin.POST("/prompts/publish", controller.PublishNacosPromptAdmin)
			nacosAdmin.POST("/prompts/labels", controller.UpdateNacosPromptLabelsAdmin)
			nacosAdmin.DELETE("/prompts/item", controller.DeleteNacosPromptAdmin)
			nacosAdmin.GET("/pipelines", controller.ListNacosPipelinesAdmin)
			nacosAdmin.GET("/pipelines/detail", controller.GetNacosPipelineDetailAdmin)
			nacosAdmin.POST("/pipelines/run-scan", controller.RunNacosPipelineScanAdmin)
			nacosAdmin.GET("/agentspecs", controller.ListNacosAgentSpecsAdmin)
			nacosAdmin.GET("/users/:id/acl", controller.GetNacosUserACL)
		}
		nacosRootACL := apiRouter.Group("/nacos")
		nacosRootACL.Use(middleware.RootAuth())
		{
			nacosRootACL.PUT("/users/:id/acl", controller.PutNacosUserACL)
		}
	}
}
