package geminiv2

// https://ai.google.dev/models/gemini

var ModelList = []string{
	"gemini-2.0-flash",
	"gemini-2.0-flash-001",
	"gemini-2.0-flash-exp-image-generation",
	"gemini-2.0-flash-lite",
	"gemini-2.0-flash-lite-001",
	"gemini-2.5-flash",
	"gemini-2.5-flash-lite",
	"gemini-2.5-flash-lite-preview-09-2025",
	"gemini-2.5-flash-native-audio-latest",
	"gemini-2.5-flash-native-audio-preview-09-2025",
	"gemini-2.5-flash-native-audio-preview-12-2025",
	"gemini-2.5-pro",
	"gemini-2.5-pro-preview",
	"gemini-2.5-pro-preview-05-06",
	"gemini-3-flash-preview",
	"gemini-3-pro-image-preview",
	"gemini-3-pro-preview",
	"gemini-3.1-flash-image-preview",
	"gemini-3.1-flash-lite",
	"gemini-3.1-flash-lite-preview",
	"gemini-3.1-flash-live-preview",
	"gemini-3.1-pro-preview",
	"gemini-3.1-pro-preview-customtools",
	"gemini-3.5-flash",
	"gemini-embedding-001",
	"gemini-exp-1206",
	"gemini-flash-latest",
	"gemini-flash-lite-latest",
	"gemini-pro-latest",
	"gemma-2-27b-it",
	"gemma-3-12b-it",
	"gemma-3-27b-it",
	"gemma-3-4b-it",
	"gemma-3n-e4b-it",
	"gemma-4-26b-a4b-it",
	"gemma-4-31b-it",
	"lyria-3-clip-preview",
	"lyria-3-pro-preview",
}
