apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: one-api-worker
  namespace: one-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: one-api
      app.kubernetes.io/component: worker
